name: kur_hesapla
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.6
  dio: ^5.2.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.3

  easy_localization: ^3.0.7
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  auto_route: ^9.2.2
  fluttertoast: ^8.2.8
  flutter_easyloading: ^3.0.5

  uikit:
    path: ../uikit
  openapi:
    path: ./package/kur_hesapla_api_client
dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^9.0.0
  very_good_analysis: ^5.1.0
  analyzer: ^6.4.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/translations/
    - assets/svg/