import 'package:kur_hesapla/app/enum/currency_type.dart';
import 'package:openapi/openapi.dart';

extension CurrencyTypeMapper on CurrencyType {
  double findValue(FindLatestData data) {
    switch (this) {
      case CurrencyType.ADA:
        return data.ADA!;
      case CurrencyType.AED:
        return data.AED!;
      case CurrencyType.AFN:
        return data.AFN!;
      case CurrencyType.ALL:
        return data.ALL!;
      case CurrencyType.AMD:
        return data.AMD!;
      case CurrencyType.ANG:
        return data.ANG!;
      case CurrencyType.AOA:
        return data.AOA!;
      case CurrencyType.ARB:
        return data.ARB!;
      case CurrencyType.ARS:
        return data.ARS!;
      case CurrencyType.AUD:
        return data.AUD!;
      case CurrencyType.AVAX:
        return data.AVAX!;
      case CurrencyType.AWG:
        return data.AWG!;
      case CurrencyType.AZN:
        return data.AZN!;
      case CurrencyType.BAM:
        return data.BAM!;
      case CurrencyType.BBD:
        return data.BBD!;
      case CurrencyType.BDT:
        return data.BDT!;
      case CurrencyType.BGN:
        return data.BGN!;
      case CurrencyType.BHD:
        return data.BHD!;
      case CurrencyType.BIF:
        return data.BIF!;
      case CurrencyType.BMD:
        return data.BMD!;
      case CurrencyType.BNB:
        return data.BNB!;
      case CurrencyType.BND:
        return data.BND!;
      case CurrencyType.BOB:
        return data.BOB!;
      case CurrencyType.BRL:
        return data.BRL!;
      case CurrencyType.BSD:
        return data.BSD!;
      case CurrencyType.BTC:
        return data.BTC!;
      case CurrencyType.BTN:
        return data.BTN!;
      case CurrencyType.BWP:
        return data.BWP!;
      case CurrencyType.BYN:
        return data.BYN!;
      case CurrencyType.BYR:
        return data.BYR!;
      case CurrencyType.BZD:
        return data.BZD!;
      case CurrencyType.CAD:
        return data.CAD!;
      case CurrencyType.CDF:
        return data.CDF!;
      case CurrencyType.CHF:
        return data.CHF!;
      // case CurrencyType.CLF:
      //   return data.CLF!;
      case CurrencyType.CLP:
        return data.CLP!;
      case CurrencyType.CNY:
        return data.CNY!;
      case CurrencyType.COP:
        return data.COP!;
      case CurrencyType.CRC:
        return data.CRC!;
      case CurrencyType.CUC:
        return data.CUC!;
      case CurrencyType.CUP:
        return data.CUP!;
      case CurrencyType.CVE:
        return data.CVE!;
      case CurrencyType.CZK:
        return data.CZK!;
      case CurrencyType.DAI:
        return data.DAI!;
      case CurrencyType.DJF:
        return data.DJF!;
      case CurrencyType.DKK:
        return data.DKK!;
      case CurrencyType.DOP:
        return data.DOP!;
      case CurrencyType.DOT:
        return data.DOT!;
      case CurrencyType.DZD:
        return data.DZD!;
      case CurrencyType.EGP:
        return data.EGP!;
      case CurrencyType.ERN:
        return data.ERN!;
      case CurrencyType.ETB:
        return data.ETB!;
      case CurrencyType.ETH:
        return data.ETH!;
      case CurrencyType.EUR:
        return data.EUR!;
      case CurrencyType.FJD:
        return data.FJD!;
      case CurrencyType.FKP:
        return data.FKP!;
      case CurrencyType.GBP:
        return data.GBP!;
      case CurrencyType.GEL:
        return data.GEL!;
      case CurrencyType.GGP:
        return data.GGP!;
      case CurrencyType.GHS:
        return data.GHS!;
      case CurrencyType.GIP:
        return data.GIP!;
      case CurrencyType.GMD:
        return data.GMD!;
      case CurrencyType.GNF:
        return data.GNF!;
      case CurrencyType.GTQ:
        return data.GTQ!;
      case CurrencyType.GYD:
        return data.GYD!;
      case CurrencyType.HKD:
        return data.HKD!;
      case CurrencyType.HNL:
        return data.HNL!;
      case CurrencyType.HRK:
        return data.HRK!;
      case CurrencyType.HTG:
        return data.HTG!;
      case CurrencyType.HUF:
        return data.HUF!;
      case CurrencyType.IDR:
        return data.IDR!;
      case CurrencyType.ILS:
        return data.ILS!;
      case CurrencyType.IMP:
        return data.IMP!;
      case CurrencyType.INR:
        return data.INR!;
      case CurrencyType.IQD:
        return data.IQD!;
      case CurrencyType.IRR:
        return data.IRR!;
      case CurrencyType.ISK:
        return data.ISK!;
      case CurrencyType.JEP:
        return data.JEP!;
      case CurrencyType.JMD:
        return data.JMD!;
      case CurrencyType.JOD:
        return data.JOD!;
      case CurrencyType.JPY:
        return data.JPY!;
      case CurrencyType.KES:
        return data.KES!;
      case CurrencyType.KGS:
        return data.KGS!;
      case CurrencyType.KHR:
        return data.KHR!;
      case CurrencyType.KMF:
        return data.KMF!;
      case CurrencyType.KPW:
        return data.KPW!;
      case CurrencyType.KRW:
        return data.KRW!;
      case CurrencyType.KWD:
        return data.KWD!;
      case CurrencyType.KYD:
        return data.KYD!;
      case CurrencyType.KZT:
        return data.KZT!;
      case CurrencyType.LAK:
        return data.LAK!;
      case CurrencyType.LBP:
        return data.LBP!;
      case CurrencyType.LKR:
        return data.LKR!;
      case CurrencyType.LRD:
        return data.LRD!;
      case CurrencyType.LSL:
        return data.LSL!;
      case CurrencyType.LTC:
        return data.LTC!;
      case CurrencyType.LTL:
        return data.LTL!;
      case CurrencyType.LVL:
        return data.LVL!;
      case CurrencyType.LYD:
        return data.LYD!;
      case CurrencyType.MAD:
        return data.MAD!;
      case CurrencyType.MATIC:
        return data.MATIC!;
      case CurrencyType.MDL:
        return data.MDL!;
      case CurrencyType.MGA:
        return data.MGA!;
      case CurrencyType.MKD:
        return data.MKD!;
      case CurrencyType.MMK:
        return data.MMK!;
      case CurrencyType.MNT:
        return data.MNT!;
      case CurrencyType.MOP:
        return data.MOP!;
      case CurrencyType.MRO:
        return data.MRO!;
      case CurrencyType.MRU:
        return data.MRU!;
      case CurrencyType.MUR:
        return data.MUR!;
      case CurrencyType.MVR:
        return data.MVR!;
      case CurrencyType.MWK:
        return data.MWK!;
      case CurrencyType.MXN:
        return data.MXN!;
      case CurrencyType.MYR:
        return data.MYR!;
      case CurrencyType.MZN:
        return data.MZN!;
      case CurrencyType.NAD:
        return data.NAD!;
      case CurrencyType.NGN:
        return data.NGN!;
      case CurrencyType.NIO:
        return data.NIO!;
      case CurrencyType.NOK:
        return data.NOK!;
      case CurrencyType.NPR:
        return data.NPR!;
      case CurrencyType.NZD:
        return data.NZD!;
      case CurrencyType.OMR:
        return data.OMR!;
      case CurrencyType.OP:
        return data.OP!;
      case CurrencyType.PAB:
        return data.PAB!;
      case CurrencyType.PEN:
        return data.PEN!;
      case CurrencyType.PGK:
        return data.PGK!;
      case CurrencyType.PHP:
        return data.PHP!;
      case CurrencyType.PKR:
        return data.PKR!;
      case CurrencyType.PLN:
        return data.PLN!;
      case CurrencyType.PYG:
        return data.PYG!;
      case CurrencyType.QAR:
        return data.QAR!;
      case CurrencyType.RON:
        return data.RON!;
      case CurrencyType.RSD:
        return data.RSD!;
      case CurrencyType.RUB:
        return data.RUB!;
      case CurrencyType.RWF:
        return data.RWF!;
      case CurrencyType.SAR:
        return data.SAR!;
      case CurrencyType.SBD:
        return data.SBD!;
      case CurrencyType.SCR:
        return data.SCR!;
      case CurrencyType.SDG:
        return data.SDG!;
      case CurrencyType.SEK:
        return data.SEK!;
      case CurrencyType.SGD:
        return data.SGD!;
      case CurrencyType.SHP:
        return data.SHP!;
      case CurrencyType.SLL:
        return data.SLL!;
      case CurrencyType.SOL:
        return data.SOL!;
      case CurrencyType.SOS:
        return data.SOS!;
      case CurrencyType.SRD:
        return data.SRD!;
      case CurrencyType.STD:
        return data.STD!;
      case CurrencyType.STN:
        return data.STN!;
      case CurrencyType.SVC:
        return data.SVC!;
      case CurrencyType.SYP:
        return data.SYP!;
      case CurrencyType.SZL:
        return data.SZL!;
      case CurrencyType.THB:
        return data.THB!;
      case CurrencyType.TJS:
        return data.TJS!;
      case CurrencyType.TMT:
        return data.TMT!;
      case CurrencyType.TND:
        return data.TND!;
      case CurrencyType.TOP:
        return data.TOP!;
      case CurrencyType.TRY:
        return data.TRY!;
      case CurrencyType.TTD:
        return data.TTD!;
      case CurrencyType.TWD:
        return data.TWD!;
      case CurrencyType.TZS:
        return data.TZS!;
      case CurrencyType.UAH:
        return data.UAH!;
      case CurrencyType.UGX:
        return data.UGX!;
      case CurrencyType.USD:
        return data.USD!;
      case CurrencyType.USDC:
        return data.USDC!;
      case CurrencyType.USDT:
        return data.USDT!;
      case CurrencyType.UYU:
        return data.UYU!;
      case CurrencyType.UZS:
        return data.UZS!;
      case CurrencyType.VEF:
        return data.VEF!;
      case CurrencyType.VES:
        return data.VES!;
      case CurrencyType.VND:
        return data.VND!;
      case CurrencyType.VUV:
        return data.VUV!;
      case CurrencyType.WST:
        return data.WST!;
      case CurrencyType.XAF:
        return data.XAF!;
      case CurrencyType.XAG:
        return data.XAG!;
      case CurrencyType.XAU:
        return data.XAU!;
      case CurrencyType.XCD:
        return data.XCD!;
      case CurrencyType.XDR:
        return data.XDR!;
      case CurrencyType.XOF:
        return data.XOF!;
      case CurrencyType.XPD:
        return data.XPD!;
      case CurrencyType.XPF:
        return data.XPF!;
      case CurrencyType.XPT:
        return data.XPT!;
      case CurrencyType.XRP:
        return data.XRP!;
      case CurrencyType.YER:
        return data.YER!;
      case CurrencyType.ZAR:
        return data.ZAR!;
      case CurrencyType.ZMK:
        return data.ZMK!;
      case CurrencyType.ZMW:
        return data.ZMW!;
      case CurrencyType.ZWL:
        return data.ZWL!;
    }
  }
}
