import 'package:kur_hesapla/app/enum/currency_type.dart';
import 'package:kur_hesapla/generated/assets.gen.dart';
import 'package:kur_hesapla_api/kur_hesapla_api.dart';

extension CurrencyTypeMapper on CurrencyType {
  double findValueFindLatestData(FindLatestData data) {
    switch (this) {
      case CurrencyType.ADA:
        return data.ADA!;
      case CurrencyType.AED:
        return data.AED!;
      case CurrencyType.AFN:
        return data.AFN!;
      case CurrencyType.ALL:
        return data.ALL!;
      case CurrencyType.AMD:
        return data.AMD!;
      case CurrencyType.ANG:
        return data.ANG!;
      case CurrencyType.AOA:
        return data.AOA!;
      case CurrencyType.ARB:
        return data.ARB!;
      case CurrencyType.ARS:
        return data.ARS!;
      case CurrencyType.AUD:
        return data.AUD!;
      case CurrencyType.AVAX:
        return data.AVAX!;
      case CurrencyType.AWG:
        return data.AWG!;
      case CurrencyType.AZN:
        return data.AZN!;
      case CurrencyType.BAM:
        return data.BAM!;
      case CurrencyType.BBD:
        return data.BBD!;
      case CurrencyType.BDT:
        return data.BDT!;
      case CurrencyType.BGN:
        return data.BGN!;
      case CurrencyType.BHD:
        return data.BHD!;
      case CurrencyType.BIF:
        return data.BIF!;
      case CurrencyType.BMD:
        return data.BMD!;
      case CurrencyType.BNB:
        return data.BNB!;
      case CurrencyType.BND:
        return data.BND!;
      case CurrencyType.BOB:
        return data.BOB!;
      case CurrencyType.BRL:
        return data.BRL!;
      case CurrencyType.BSD:
        return data.BSD!;
      case CurrencyType.BTC:
        return data.BTC!;
      case CurrencyType.BTN:
        return data.BTN!;
      case CurrencyType.BWP:
        return data.BWP!;
      case CurrencyType.BYN:
        return data.BYN!;
      case CurrencyType.BYR:
        return data.BYR!;
      case CurrencyType.BZD:
        return data.BZD!;
      case CurrencyType.CAD:
        return data.CAD!;
      case CurrencyType.CDF:
        return data.CDF!;
      case CurrencyType.CHF:
        return data.CHF!;
      // case CurrencyType.CLF:
      //   return data.CLF!;
      case CurrencyType.CLP:
        return data.CLP!;
      case CurrencyType.CNY:
        return data.CNY!;
      case CurrencyType.COP:
        return data.COP!;
      case CurrencyType.CRC:
        return data.CRC!;
      case CurrencyType.CUC:
        return data.CUC!;
      case CurrencyType.CUP:
        return data.CUP!;
      case CurrencyType.CVE:
        return data.CVE!;
      case CurrencyType.CZK:
        return data.CZK!;
      case CurrencyType.DAI:
        return data.DAI!;
      case CurrencyType.DJF:
        return data.DJF!;
      case CurrencyType.DKK:
        return data.DKK!;
      case CurrencyType.DOP:
        return data.DOP!;
      case CurrencyType.DOT:
        return data.DOT!;
      case CurrencyType.DZD:
        return data.DZD!;
      case CurrencyType.EGP:
        return data.EGP!;
      case CurrencyType.ERN:
        return data.ERN!;
      case CurrencyType.ETB:
        return data.ETB!;
      case CurrencyType.ETH:
        return data.ETH!;
      case CurrencyType.EUR:
        return data.EUR!;
      case CurrencyType.FJD:
        return data.FJD!;
      case CurrencyType.FKP:
        return data.FKP!;
      case CurrencyType.GBP:
        return data.GBP!;
      case CurrencyType.GEL:
        return data.GEL!;
      case CurrencyType.GGP:
        return data.GGP!;
      case CurrencyType.GHS:
        return data.GHS!;
      case CurrencyType.GIP:
        return data.GIP!;
      case CurrencyType.GMD:
        return data.GMD!;
      case CurrencyType.GNF:
        return data.GNF!;
      case CurrencyType.GTQ:
        return data.GTQ!;
      case CurrencyType.GYD:
        return data.GYD!;
      case CurrencyType.HKD:
        return data.HKD!;
      case CurrencyType.HNL:
        return data.HNL!;
      case CurrencyType.HRK:
        return data.HRK!;
      case CurrencyType.HTG:
        return data.HTG!;
      case CurrencyType.HUF:
        return data.HUF!;
      case CurrencyType.IDR:
        return data.IDR!;
      case CurrencyType.ILS:
        return data.ILS!;
      case CurrencyType.IMP:
        return data.IMP!;
      case CurrencyType.INR:
        return data.INR!;
      case CurrencyType.IQD:
        return data.IQD!;
      case CurrencyType.IRR:
        return data.IRR!;
      case CurrencyType.ISK:
        return data.ISK!;
      case CurrencyType.JEP:
        return data.JEP!;
      case CurrencyType.JMD:
        return data.JMD!;
      case CurrencyType.JOD:
        return data.JOD!;
      case CurrencyType.JPY:
        return data.JPY!;
      case CurrencyType.KES:
        return data.KES!;
      case CurrencyType.KGS:
        return data.KGS!;
      case CurrencyType.KHR:
        return data.KHR!;
      case CurrencyType.KMF:
        return data.KMF!;
      case CurrencyType.KPW:
        return data.KPW!;
      case CurrencyType.KRW:
        return data.KRW!;
      case CurrencyType.KWD:
        return data.KWD!;
      case CurrencyType.KYD:
        return data.KYD!;
      case CurrencyType.KZT:
        return data.KZT!;
      case CurrencyType.LAK:
        return data.LAK!;
      case CurrencyType.LBP:
        return data.LBP!;
      case CurrencyType.LKR:
        return data.LKR!;
      case CurrencyType.LRD:
        return data.LRD!;
      case CurrencyType.LSL:
        return data.LSL!;
      case CurrencyType.LTC:
        return data.LTC!;
      case CurrencyType.LTL:
        return data.LTL!;
      case CurrencyType.LVL:
        return data.LVL!;
      case CurrencyType.LYD:
        return data.LYD!;
      case CurrencyType.MAD:
        return data.MAD!;
      case CurrencyType.MATIC:
        return data.MATIC!;
      case CurrencyType.MDL:
        return data.MDL!;
      case CurrencyType.MGA:
        return data.MGA!;
      case CurrencyType.MKD:
        return data.MKD!;
      case CurrencyType.MMK:
        return data.MMK!;
      case CurrencyType.MNT:
        return data.MNT!;
      case CurrencyType.MOP:
        return data.MOP!;
      case CurrencyType.MRO:
        return data.MRO!;
      case CurrencyType.MRU:
        return data.MRU!;
      case CurrencyType.MUR:
        return data.MUR!;
      case CurrencyType.MVR:
        return data.MVR!;
      case CurrencyType.MWK:
        return data.MWK!;
      case CurrencyType.MXN:
        return data.MXN!;
      case CurrencyType.MYR:
        return data.MYR!;
      case CurrencyType.MZN:
        return data.MZN!;
      case CurrencyType.NAD:
        return data.NAD!;
      case CurrencyType.NGN:
        return data.NGN!;
      case CurrencyType.NIO:
        return data.NIO!;
      case CurrencyType.NOK:
        return data.NOK!;
      case CurrencyType.NPR:
        return data.NPR!;
      case CurrencyType.NZD:
        return data.NZD!;
      case CurrencyType.OMR:
        return data.OMR!;
      case CurrencyType.OP:
        return data.OP!;
      case CurrencyType.PAB:
        return data.PAB!;
      case CurrencyType.PEN:
        return data.PEN!;
      case CurrencyType.PGK:
        return data.PGK!;
      case CurrencyType.PHP:
        return data.PHP!;
      case CurrencyType.PKR:
        return data.PKR!;
      case CurrencyType.PLN:
        return data.PLN!;
      case CurrencyType.PYG:
        return data.PYG!;
      case CurrencyType.QAR:
        return data.QAR!;
      case CurrencyType.RON:
        return data.RON!;
      case CurrencyType.RSD:
        return data.RSD!;
      case CurrencyType.RUB:
        return data.RUB!;
      case CurrencyType.RWF:
        return data.RWF!;
      case CurrencyType.SAR:
        return data.SAR!;
      case CurrencyType.SBD:
        return data.SBD!;
      case CurrencyType.SCR:
        return data.SCR!;
      case CurrencyType.SDG:
        return data.SDG!;
      case CurrencyType.SEK:
        return data.SEK!;
      case CurrencyType.SGD:
        return data.SGD!;
      case CurrencyType.SHP:
        return data.SHP!;
      case CurrencyType.SLL:
        return data.SLL!;
      case CurrencyType.SOL:
        return data.SOL!;
      case CurrencyType.SOS:
        return data.SOS!;
      case CurrencyType.SRD:
        return data.SRD!;
      case CurrencyType.STD:
        return data.STD!;
      case CurrencyType.STN:
        return data.STN!;
      case CurrencyType.SVC:
        return data.SVC!;
      case CurrencyType.SYP:
        return data.SYP!;
      case CurrencyType.SZL:
        return data.SZL!;
      case CurrencyType.THB:
        return data.THB!;
      case CurrencyType.TJS:
        return data.TJS!;
      case CurrencyType.TMT:
        return data.TMT!;
      case CurrencyType.TND:
        return data.TND!;
      case CurrencyType.TOP:
        return data.TOP!;
      case CurrencyType.TRY:
        return data.TRY!;
      case CurrencyType.TTD:
        return data.TTD!;
      case CurrencyType.TWD:
        return data.TWD!;
      case CurrencyType.TZS:
        return data.TZS!;
      case CurrencyType.UAH:
        return data.UAH!;
      case CurrencyType.UGX:
        return data.UGX!;
      case CurrencyType.USD:
        return data.USD!;
      case CurrencyType.USDC:
        return data.USDC!;
      case CurrencyType.USDT:
        return data.USDT!;
      case CurrencyType.UYU:
        return data.UYU!;
      case CurrencyType.UZS:
        return data.UZS!;
      case CurrencyType.VEF:
        return data.VEF!;
      case CurrencyType.VES:
        return data.VES!;
      case CurrencyType.VND:
        return data.VND!;
      case CurrencyType.VUV:
        return data.VUV!;
      case CurrencyType.WST:
        return data.WST!;
      case CurrencyType.XAF:
        return data.XAF!;
      case CurrencyType.XAG:
        return data.XAG!;
      case CurrencyType.XAU:
        return data.XAU!;
      case CurrencyType.XCD:
        return data.XCD!;
      case CurrencyType.XDR:
        return data.XDR!;
      case CurrencyType.XOF:
        return data.XOF!;
      case CurrencyType.XPD:
        return data.XPD!;
      case CurrencyType.XPF:
        return data.XPF!;
      case CurrencyType.XPT:
        return data.XPT!;
      case CurrencyType.XRP:
        return data.XRP!;
      case CurrencyType.YER:
        return data.YER!;
      case CurrencyType.ZAR:
        return data.ZAR!;
      case CurrencyType.ZMK:
        return data.ZMK!;
      case CurrencyType.ZMW:
        return data.ZMW!;
      case CurrencyType.ZWL:
        return data.ZWL!;
    }
  }

  double findValueFromHistoricalPricesData(HistoricalPricesData data) {
    switch (this) {
      case CurrencyType.ADA:
        return data.ADA!;
      case CurrencyType.AED:
        return data.AED!;
      case CurrencyType.AFN:
        return data.AFN!;
      case CurrencyType.ALL:
        return data.ALL!;
      case CurrencyType.AMD:
        return data.AMD!;
      case CurrencyType.ANG:
        return data.ANG!;
      case CurrencyType.AOA:
        return data.AOA!;
      case CurrencyType.ARB:
        return data.ARB!;
      case CurrencyType.ARS:
        return data.ARS!;
      case CurrencyType.AUD:
        return data.AUD!;
      case CurrencyType.AVAX:
        return data.AVAX!;
      case CurrencyType.AWG:
        return data.AWG!;
      case CurrencyType.AZN:
        return data.AZN!;
      case CurrencyType.BAM:
        return data.BAM!;
      case CurrencyType.BBD:
        return data.BBD!;
      case CurrencyType.BDT:
        return data.BDT!;
      case CurrencyType.BGN:
        return data.BGN!;
      case CurrencyType.BHD:
        return data.BHD!;
      case CurrencyType.BIF:
        return data.BIF!;
      case CurrencyType.BMD:
        return data.BMD!;
      case CurrencyType.BNB:
        return data.BNB!;
      case CurrencyType.BND:
        return data.BND!;
      case CurrencyType.BOB:
        return data.BOB!;
      case CurrencyType.BRL:
        return data.BRL!;
      case CurrencyType.BSD:
        return data.BSD!;
      case CurrencyType.BTC:
        return data.BTC!;
      case CurrencyType.BTN:
        return data.BTN!;
      case CurrencyType.BWP:
        return data.BWP!;
      case CurrencyType.BYN:
        return data.BYN!;
      case CurrencyType.BYR:
        return data.BYR!;
      case CurrencyType.BZD:
        return data.BZD!;
      case CurrencyType.CAD:
        return data.CAD!;
      case CurrencyType.CDF:
        return data.CDF!;
      case CurrencyType.CHF:
        return data.CHF!;
      // case CurrencyType.CLF:
      //   return data.CLF!;
      case CurrencyType.CLP:
        return data.CLP!;
      case CurrencyType.CNY:
        return data.CNY!;
      case CurrencyType.COP:
        return data.COP!;
      case CurrencyType.CRC:
        return data.CRC!;
      case CurrencyType.CUC:
        return data.CUC!;
      case CurrencyType.CUP:
        return data.CUP!;
      case CurrencyType.CVE:
        return data.CVE!;
      case CurrencyType.CZK:
        return data.CZK!;
      case CurrencyType.DAI:
        return data.DAI!;
      case CurrencyType.DJF:
        return data.DJF!;
      case CurrencyType.DKK:
        return data.DKK!;
      case CurrencyType.DOP:
        return data.DOP!;
      case CurrencyType.DOT:
        return data.DOT!;
      case CurrencyType.DZD:
        return data.DZD!;
      case CurrencyType.EGP:
        return data.EGP!;
      case CurrencyType.ERN:
        return data.ERN!;
      case CurrencyType.ETB:
        return data.ETB!;
      case CurrencyType.ETH:
        return data.ETH!;
      case CurrencyType.EUR:
        return data.EUR!;
      case CurrencyType.FJD:
        return data.FJD!;
      case CurrencyType.FKP:
        return data.FKP!;
      case CurrencyType.GBP:
        return data.GBP!;
      case CurrencyType.GEL:
        return data.GEL!;
      case CurrencyType.GGP:
        return data.GGP!;
      case CurrencyType.GHS:
        return data.GHS!;
      case CurrencyType.GIP:
        return data.GIP!;
      case CurrencyType.GMD:
        return data.GMD!;
      case CurrencyType.GNF:
        return data.GNF!;
      case CurrencyType.GTQ:
        return data.GTQ!;
      case CurrencyType.GYD:
        return data.GYD!;
      case CurrencyType.HKD:
        return data.HKD!;
      case CurrencyType.HNL:
        return data.HNL!;
      case CurrencyType.HRK:
        return data.HRK!;
      case CurrencyType.HTG:
        return data.HTG!;
      case CurrencyType.HUF:
        return data.HUF!;
      case CurrencyType.IDR:
        return data.IDR!;
      case CurrencyType.ILS:
        return data.ILS!;
      case CurrencyType.IMP:
        return data.IMP!;
      case CurrencyType.INR:
        return data.INR!;
      case CurrencyType.IQD:
        return data.IQD!;
      case CurrencyType.IRR:
        return data.IRR!;
      case CurrencyType.ISK:
        return data.ISK!;
      case CurrencyType.JEP:
        return data.JEP!;
      case CurrencyType.JMD:
        return data.JMD!;
      case CurrencyType.JOD:
        return data.JOD!;
      case CurrencyType.JPY:
        return data.JPY!;
      case CurrencyType.KES:
        return data.KES!;
      case CurrencyType.KGS:
        return data.KGS!;
      case CurrencyType.KHR:
        return data.KHR!;
      case CurrencyType.KMF:
        return data.KMF!;
      case CurrencyType.KPW:
        return data.KPW!;
      case CurrencyType.KRW:
        return data.KRW!;
      case CurrencyType.KWD:
        return data.KWD!;
      case CurrencyType.KYD:
        return data.KYD!;
      case CurrencyType.KZT:
        return data.KZT!;
      case CurrencyType.LAK:
        return data.LAK!;
      case CurrencyType.LBP:
        return data.LBP!;
      case CurrencyType.LKR:
        return data.LKR!;
      case CurrencyType.LRD:
        return data.LRD!;
      case CurrencyType.LSL:
        return data.LSL!;
      case CurrencyType.LTC:
        return data.LTC!;
      case CurrencyType.LTL:
        return data.LTL!;
      case CurrencyType.LVL:
        return data.LVL!;
      case CurrencyType.LYD:
        return data.LYD!;
      case CurrencyType.MAD:
        return data.MAD!;
      case CurrencyType.MATIC:
        return data.MATIC!;
      case CurrencyType.MDL:
        return data.MDL!;
      case CurrencyType.MGA:
        return data.MGA!;
      case CurrencyType.MKD:
        return data.MKD!;
      case CurrencyType.MMK:
        return data.MMK!;
      case CurrencyType.MNT:
        return data.MNT!;
      case CurrencyType.MOP:
        return data.MOP!;
      case CurrencyType.MRO:
        return data.MRO!;
      case CurrencyType.MRU:
        return data.MRU!;
      case CurrencyType.MUR:
        return data.MUR!;
      case CurrencyType.MVR:
        return data.MVR!;
      case CurrencyType.MWK:
        return data.MWK!;
      case CurrencyType.MXN:
        return data.MXN!;
      case CurrencyType.MYR:
        return data.MYR!;
      case CurrencyType.MZN:
        return data.MZN!;
      case CurrencyType.NAD:
        return data.NAD!;
      case CurrencyType.NGN:
        return data.NGN!;
      case CurrencyType.NIO:
        return data.NIO!;
      case CurrencyType.NOK:
        return data.NOK!;
      case CurrencyType.NPR:
        return data.NPR!;
      case CurrencyType.NZD:
        return data.NZD!;
      case CurrencyType.OMR:
        return data.OMR!;
      case CurrencyType.OP:
        return data.OP!;
      case CurrencyType.PAB:
        return data.PAB!;
      case CurrencyType.PEN:
        return data.PEN!;
      case CurrencyType.PGK:
        return data.PGK!;
      case CurrencyType.PHP:
        return data.PHP!;
      case CurrencyType.PKR:
        return data.PKR!;
      case CurrencyType.PLN:
        return data.PLN!;
      case CurrencyType.PYG:
        return data.PYG!;
      case CurrencyType.QAR:
        return data.QAR!;
      case CurrencyType.RON:
        return data.RON!;
      case CurrencyType.RSD:
        return data.RSD!;
      case CurrencyType.RUB:
        return data.RUB!;
      case CurrencyType.RWF:
        return data.RWF!;
      case CurrencyType.SAR:
        return data.SAR!;
      case CurrencyType.SBD:
        return data.SBD!;
      case CurrencyType.SCR:
        return data.SCR!;
      case CurrencyType.SDG:
        return data.SDG!;
      case CurrencyType.SEK:
        return data.SEK!;
      case CurrencyType.SGD:
        return data.SGD!;
      case CurrencyType.SHP:
        return data.SHP!;
      case CurrencyType.SLL:
        return data.SLL!;
      case CurrencyType.SOL:
        return data.SOL!;
      case CurrencyType.SOS:
        return data.SOS!;
      case CurrencyType.SRD:
        return data.SRD!;
      case CurrencyType.STD:
        return data.STD!;
      case CurrencyType.STN:
        return data.STN!;
      case CurrencyType.SVC:
        return data.SVC!;
      case CurrencyType.SYP:
        return data.SYP!;
      case CurrencyType.SZL:
        return data.SZL!;
      case CurrencyType.THB:
        return data.THB!;
      case CurrencyType.TJS:
        return data.TJS!;
      case CurrencyType.TMT:
        return data.TMT!;
      case CurrencyType.TND:
        return data.TND!;
      case CurrencyType.TOP:
        return data.TOP!;
      case CurrencyType.TRY:
        return data.TRY!;
      case CurrencyType.TTD:
        return data.TTD!;
      case CurrencyType.TWD:
        return data.TWD!;
      case CurrencyType.TZS:
        return data.TZS!;
      case CurrencyType.UAH:
        return data.UAH!;
      case CurrencyType.UGX:
        return data.UGX!;
      case CurrencyType.USD:
        return data.USD!;
      case CurrencyType.USDC:
        return data.USDC!;
      case CurrencyType.USDT:
        return data.USDT!;
      case CurrencyType.UYU:
        return data.UYU!;
      case CurrencyType.UZS:
        return data.UZS!;
      case CurrencyType.VEF:
        return data.VEF!;
      case CurrencyType.VES:
        return data.VES!;
      case CurrencyType.VND:
        return data.VND!;
      case CurrencyType.VUV:
        return data.VUV!;
      case CurrencyType.WST:
        return data.WST!;
      case CurrencyType.XAF:
        return data.XAF!;
      case CurrencyType.XAG:
        return data.XAG!;
      case CurrencyType.XAU:
        return data.XAU!;
      case CurrencyType.XCD:
        return data.XCD!;
      case CurrencyType.XDR:
        return data.XDR!;
      case CurrencyType.XOF:
        return data.XOF!;
      case CurrencyType.XPD:
        return data.XPD!;
      case CurrencyType.XPF:
        return data.XPF!;
      case CurrencyType.XPT:
        return data.XPT!;
      case CurrencyType.XRP:
        return data.XRP!;
      case CurrencyType.YER:
        return data.YER!;
      case CurrencyType.ZAR:
        return data.ZAR!;
      case CurrencyType.ZMK:
        return data.ZMK!;
      case CurrencyType.ZMW:
        return data.ZMW!;
      case CurrencyType.ZWL:
        return data.ZWL!;
    }
  }

  SvgGenImage? get getSvgGenImage {
    switch (this) {
      case CurrencyType.ADA:
        return null;
      case CurrencyType.AED:
        return Assets.svg.flags.aedicon;
      case CurrencyType.AFN:
        return Assets.svg.flags.afnicon;
      case CurrencyType.ALL:
        return null;

      case CurrencyType.AMD:
        return Assets.svg.flags.amdicon;
      case CurrencyType.ANG:
        return Assets.svg.flags.angicon;
      case CurrencyType.AOA:
        return Assets.svg.flags.aoaicon;
      case CurrencyType.ARB:
        return null;

      case CurrencyType.ARS:
        return Assets.svg.flags.arsicon;
      case CurrencyType.AUD:
        return Assets.svg.flags.audicon;
      case CurrencyType.AVAX:
        return null;

      case CurrencyType.AWG:
        return Assets.svg.flags.awgicon;
      case CurrencyType.AZN:
        return Assets.svg.flags.aznicon;
      case CurrencyType.BAM:
        return Assets.svg.flags.bamicon;
      case CurrencyType.BBD:
        return Assets.svg.flags.bbdicon;
      case CurrencyType.BDT:
        return Assets.svg.flags.bdticon;
      case CurrencyType.BGN:
        return Assets.svg.flags.bgnicon;
      case CurrencyType.BHD:
        return Assets.svg.flags.bhdicon;
      case CurrencyType.BIF:
        return Assets.svg.flags.bificon;
      case CurrencyType.BMD:
        return Assets.svg.flags.bmdicon;
      case CurrencyType.BNB:
        return null;

      case CurrencyType.BND:
        return Assets.svg.flags.bndicon;
      case CurrencyType.BOB:
        return Assets.svg.flags.bobicon;
      case CurrencyType.BRL:
        return Assets.svg.flags.brlicon;
      case CurrencyType.BSD:
        return Assets.svg.flags.bsdicon;
      case CurrencyType.BTC:
        return null;

      case CurrencyType.BTN:
        return Assets.svg.flags.btnicon;
      case CurrencyType.BWP:
        return Assets.svg.flags.bwpicon;
      case CurrencyType.BYN:
        return Assets.svg.flags.bynicon;
      case CurrencyType.BYR:
        return Assets.svg.flags.byricon;
      case CurrencyType.BZD:
        return Assets.svg.flags.bzdicon;
      case CurrencyType.CAD:
        return Assets.svg.flags.cadicon;
      case CurrencyType.CDF:
        return Assets.svg.flags.cdficon;
      case CurrencyType.CHF:
        return Assets.svg.flags.chficon;
      // case CurrencyType.CLF:
      //   return Assets.svg.flags.clficon
      case CurrencyType.CLP:
        return Assets.svg.flags.clpicon;
      case CurrencyType.CNY:
        return Assets.svg.flags.cnyicon;
      case CurrencyType.COP:
        return Assets.svg.flags.copicon;
      case CurrencyType.CRC:
        return Assets.svg.flags.crcicon;
      case CurrencyType.CUC:
        return Assets.svg.flags.cucicon;
      case CurrencyType.CUP:
        return Assets.svg.flags.cupicon;
      case CurrencyType.CVE:
        return Assets.svg.flags.cveicon;
      case CurrencyType.CZK:
        return Assets.svg.flags.czkicon;
      case CurrencyType.DAI:
        return null;

      case CurrencyType.DJF:
        return Assets.svg.flags.djficon;
      case CurrencyType.DKK:
        return Assets.svg.flags.dkkicon;
      case CurrencyType.DOP:
        return Assets.svg.flags.dopicon;
      case CurrencyType.DOT:
        return null;

      case CurrencyType.DZD:
        return Assets.svg.flags.dzdicon;
      case CurrencyType.EGP:
        return Assets.svg.flags.egpicon;
      case CurrencyType.ERN:
        return Assets.svg.flags.ernicon;
      case CurrencyType.ETB:
        return Assets.svg.flags.etbicon;
      case CurrencyType.ETH:
        return null;

      case CurrencyType.EUR:
        return Assets.svg.flags.euricon;
      case CurrencyType.FJD:
        return Assets.svg.flags.fjdicon;
      case CurrencyType.FKP:
        return Assets.svg.flags.fkpicon;
      case CurrencyType.GBP:
        return Assets.svg.flags.gbpicon;
      case CurrencyType.GEL:
        return Assets.svg.flags.gelicon;
      case CurrencyType.GGP:
        return Assets.svg.flags.ggpicon;
      case CurrencyType.GHS:
        return Assets.svg.flags.ghsicon;
      case CurrencyType.GIP:
        return Assets.svg.flags.gipicon;
      case CurrencyType.GMD:
        return Assets.svg.flags.gmdicon;
      case CurrencyType.GNF:
        return Assets.svg.flags.gnficon;
      case CurrencyType.GTQ:
        return Assets.svg.flags.gtqicon;
      case CurrencyType.GYD:
        return Assets.svg.flags.gydicon;
      case CurrencyType.HKD:
        return Assets.svg.flags.hkdicon;
      case CurrencyType.HNL:
        return Assets.svg.flags.hnlicon;
      case CurrencyType.HRK:
        return null;

      case CurrencyType.HTG:
        return Assets.svg.flags.htgicon;
      case CurrencyType.HUF:
        return Assets.svg.flags.huficon;
      case CurrencyType.IDR:
        return Assets.svg.flags.idricon;
      case CurrencyType.ILS:
        return Assets.svg.flags.ilsicon;
      case CurrencyType.IMP:
        return Assets.svg.flags.impicon;
      case CurrencyType.INR:
        return Assets.svg.flags.inricon;
      case CurrencyType.IQD:
        return Assets.svg.flags.iqdicon;
      case CurrencyType.IRR:
        return Assets.svg.flags.irricon;
      case CurrencyType.ISK:
        return Assets.svg.flags.iskicon;
      case CurrencyType.JEP:
        return Assets.svg.flags.jepicon;
      case CurrencyType.JMD:
        return Assets.svg.flags.jmdicon;
      case CurrencyType.JOD:
        return Assets.svg.flags.jodicon;
      case CurrencyType.JPY:
        return Assets.svg.flags.jpyicon;
      case CurrencyType.KES:
        return Assets.svg.flags.kesicon;
      case CurrencyType.KGS:
        return Assets.svg.flags.kgsicon;
      case CurrencyType.KHR:
        return Assets.svg.flags.khricon;
      case CurrencyType.KMF:
        return Assets.svg.flags.kmficon;
      case CurrencyType.KPW:
        return Assets.svg.flags.kpwicon;
      case CurrencyType.KRW:
        return Assets.svg.flags.krwicon;
      case CurrencyType.KWD:
        return Assets.svg.flags.kwdicon;
      case CurrencyType.KYD:
        return Assets.svg.flags.kydicon;
      case CurrencyType.KZT:
        return Assets.svg.flags.kzticon;
      case CurrencyType.LAK:
        return Assets.svg.flags.lakicon;
      case CurrencyType.LBP:
        return Assets.svg.flags.lbpicon;
      case CurrencyType.LKR:
        return Assets.svg.flags.lkricon;
      case CurrencyType.LRD:
        return Assets.svg.flags.lrdicon;
      case CurrencyType.LSL:
        return Assets.svg.flags.lslicon;
      case CurrencyType.LTC:
        return null;

      case CurrencyType.LTL:
        return Assets.svg.flags.ltlicon;
      case CurrencyType.LVL:
        return Assets.svg.flags.lvlicon;
      case CurrencyType.LYD:
        return Assets.svg.flags.lydicon;
      case CurrencyType.MAD:
        return Assets.svg.flags.madicon;
      case CurrencyType.MATIC:
        return null;

      case CurrencyType.MDL:
        return Assets.svg.flags.mdlicon;
      case CurrencyType.MGA:
        return Assets.svg.flags.mgaicon;
      case CurrencyType.MKD:
        return Assets.svg.flags.mkdicon;
      case CurrencyType.MMK:
        return Assets.svg.flags.mmkicon;
      case CurrencyType.MNT:
        return Assets.svg.flags.mnticon;
      case CurrencyType.MOP:
        return Assets.svg.flags.mopicon;
      case CurrencyType.MRO:
        return null;

      case CurrencyType.MRU:
        return Assets.svg.flags.mruicon;
      case CurrencyType.MUR:
        return Assets.svg.flags.muricon;
      case CurrencyType.MVR:
        return Assets.svg.flags.mvricon;
      case CurrencyType.MWK:
        return Assets.svg.flags.mwkicon;
      case CurrencyType.MXN:
        return Assets.svg.flags.mxnicon;
      case CurrencyType.MYR:
        return Assets.svg.flags.myricon;
      case CurrencyType.MZN:
        return Assets.svg.flags.mznicon;
      case CurrencyType.NAD:
        return Assets.svg.flags.nadicon;
      case CurrencyType.NGN:
        return Assets.svg.flags.ngnicon;
      case CurrencyType.NIO:
        return Assets.svg.flags.nioicon;
      case CurrencyType.NOK:
        return Assets.svg.flags.nokicon;
      case CurrencyType.NPR:
        return Assets.svg.flags.npricon;
      case CurrencyType.NZD:
        return Assets.svg.flags.nzdicon;
      case CurrencyType.OMR:
        return Assets.svg.flags.omricon;
      case CurrencyType.OP:
        return null;

      case CurrencyType.PAB:
        return Assets.svg.flags.pabicon;
      case CurrencyType.PEN:
        return Assets.svg.flags.penicon;
      case CurrencyType.PGK:
        return Assets.svg.flags.pgkicon;
      case CurrencyType.PHP:
        return Assets.svg.flags.phpicon;
      case CurrencyType.PKR:
        return Assets.svg.flags.pkricon;
      case CurrencyType.PLN:
        return Assets.svg.flags.plnicon;
      case CurrencyType.PYG:
        return Assets.svg.flags.pygicon;
      case CurrencyType.QAR:
        return Assets.svg.flags.qaricon;
      case CurrencyType.RON:
        return Assets.svg.flags.ronicon;
      case CurrencyType.RSD:
        return Assets.svg.flags.rsdicon;
      case CurrencyType.RUB:
        return Assets.svg.flags.rubicon;
      case CurrencyType.RWF:
        return Assets.svg.flags.rwficon;
      case CurrencyType.SAR:
        return Assets.svg.flags.saricon;
      case CurrencyType.SBD:
        return Assets.svg.flags.sbdicon;
      case CurrencyType.SCR:
        return Assets.svg.flags.scricon;
      case CurrencyType.SDG:
        return Assets.svg.flags.sdgicon;
      case CurrencyType.SEK:
        return Assets.svg.flags.sekicon;
      case CurrencyType.SGD:
        return Assets.svg.flags.sgdicon;
      case CurrencyType.SHP:
        return Assets.svg.flags.shpicon;
      case CurrencyType.SLL:
        return Assets.svg.flags.sllicon;
      case CurrencyType.SOL:
        return null;

      case CurrencyType.SOS:
        return Assets.svg.flags.sosicon;
      case CurrencyType.SRD:
        return Assets.svg.flags.srdicon;
      case CurrencyType.STD:
        return null;

      case CurrencyType.STN:
        return Assets.svg.flags.stnicon;
      case CurrencyType.SVC:
        return Assets.svg.flags.svcicon;
      case CurrencyType.SYP:
        return Assets.svg.flags.sypicon;
      case CurrencyType.SZL:
        return Assets.svg.flags.szlicon;
      case CurrencyType.THB:
        return Assets.svg.flags.thbicon;
      case CurrencyType.TJS:
        return Assets.svg.flags.tjsicon;
      case CurrencyType.TMT:
        return Assets.svg.flags.tmticon;
      case CurrencyType.TND:
        return Assets.svg.flags.tndicon;
      case CurrencyType.TOP:
        return Assets.svg.flags.topicon;
      case CurrencyType.TRY:
        return Assets.svg.flags.tryicon;
      case CurrencyType.TTD:
        return Assets.svg.flags.ttdicon;
      case CurrencyType.TWD:
        return Assets.svg.flags.twdicon;
      case CurrencyType.TZS:
        return Assets.svg.flags.tzsicon;
      case CurrencyType.UAH:
        return Assets.svg.flags.uahicon;
      case CurrencyType.UGX:
        return Assets.svg.flags.ugxicon;
      case CurrencyType.USD:
        return Assets.svg.flags.usdicon;
      case CurrencyType.USDC:
        return null;

      case CurrencyType.USDT:
        return null;

      case CurrencyType.UYU:
        return Assets.svg.flags.uyuicon;
      case CurrencyType.UZS:
        return Assets.svg.flags.uzsicon;
      case CurrencyType.VEF:
        return Assets.svg.flags.veficon;
      case CurrencyType.VES:
        return null;

      case CurrencyType.VND:
        return Assets.svg.flags.vndicon;
      case CurrencyType.VUV:
        return Assets.svg.flags.vuvicon;
      case CurrencyType.WST:
        return Assets.svg.flags.wsticon;
      case CurrencyType.XAF:
        return Assets.svg.flags.xaficon;
      case CurrencyType.XAG:
        return Assets.svg.flags.xagicon;
      case CurrencyType.XAU:
        return Assets.svg.flags.xauicon;
      case CurrencyType.XCD:
        return Assets.svg.flags.xcdicon;
      case CurrencyType.XDR:
        return Assets.svg.flags.xdricon;
      case CurrencyType.XOF:
        return Assets.svg.flags.xoficon;
      case CurrencyType.XPD:
        return Assets.svg.flags.xpdicon;
      case CurrencyType.XPF:
        return Assets.svg.flags.xpficon;
      case CurrencyType.XPT:
        return Assets.svg.flags.xpticon;
      case CurrencyType.XRP:
        return null;

      case CurrencyType.YER:
        return Assets.svg.flags.yericon;
      case CurrencyType.ZAR:
        return Assets.svg.flags.zaricon;
      case CurrencyType.ZMK:
        return Assets.svg.flags.zmkicon;
      case CurrencyType.ZMW:
        return Assets.svg.flags.zmwicon;
      case CurrencyType.ZWL:
        return null;
    }
  }
}
